version: "3.7"

services:
  postgres:
    image: postgres:latest
    container_name: postgres-node
    environment:
      - POSTGRES_PASSWORD=postgres
    restart: unless-stopped
    networks: 
      - ms-network
    ports:
      - "127.0.0.1:5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-node
    restart: unless-stopped
    networks: 
      - ms-network
    ports:
      - "127.0.0.1:15672:15672"
      - "127.0.0.1:5672:5672"

networks:
  ms-network:
    name: ms-network